# /opt/onyx/config/assets.yml

assets:
  # --- System Prerequisites ---
  firewall_dir:
    path: "/etc/onyx/firewall"
    type: "directory"

  ipset:
    type: "package"
    package_name: "ipset"

  # --- Intelligence Feeds ---
  sentinel_dns:
    source: "https://raw.githubusercontent.com/stevenblack/hosts/master/hosts"
    path: "/etc/unbound/unbound.conf.d/sentinel_raw.tmp"
    type: "file"

  geoblock_high_risk:
    source: "https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/refs/heads/master/ipv4/cn.cidr"
    path: "/etc/onyx/firewall/geo_block.list"
    type: "file"

  # --- Binary Tools ---
  yq_processor:
    source: "https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm"
    path: "/usr/local/bin/yq"
    type: "binary"

  xtables_addons:
    type: "package"
    # This package provides the xt_ID module required for shape obfuscation
    package_name: "xtables-addons-common"