# /opt/onyx/etc/hardening.yml
# Onyx Hardening Configuration File

hardening:
  system:
    # --- RESOURCE & PRIVACY FOUNDATIONS ---
    use_zram: true             # Toggles zram to active swap in RAM
    forensic_zero: true        # Toggles folder2ram for /var/log
    dark_mode: true            # Toggles Physical Dark Mode (LED Stealth)
    bluetooth_locked: true     # Toggles BT hardware state
    mac_stealth: false         # Toggles wlan0 MAC randomization
    mac_blend: "apple"         # Options: "apple", "samsung", "intel", "random", "off"
    ttl_masking: "windows"     # Mask router presence ("windows", "linux", "solaris")

  kernel:
    # --- ADDITIONAL STEALTH & RECON ---
    fingerprint_protection: true # net.ipv4.tcp_timestamps=0 / net.ipv4.tcp_window_scaling=1
    qname_stealth: true          # <--- DNS Privacy
    icmp_recon_defense: true     # <--- Anti-Scanning
    arp_guard: true              # <--- Internal Stealth
    icmp_stealth: true           # net.ipv4.icmp_echo_ignore_broadcasts=1

    # --- STACK HARDENING ---
    kernel_lockdown: true        # Disable the Magic SysRq debug keys and Reboot automatically 1 second after a kernel panic
    anti_spoofing: true          # net.ipv4.conf.all.rp_filter=1
    flood_protection: true       # net.ipv4.tcp_syncookies=1
    log_martians: true           # net.ipv4.conf.all.log_martians=1
    
    # --- ONYX ROUTING INTEGRITY ---
    ip_forwarding: true           # net.ipv4.ip_forward=1 (Router Function)
    disable_ipv6: true            # net.ipv6.conf.all.*.disable_ipv6=1
    ignore_redirects: true        # net.ipv4.conf.all.accept_redirects=0
    no_send_redirects: true       # net.ipv4.conf.all.send_redirects=0

  network:
    # --- APEX ONYX DEFENSIVE POSTURE ---
    default_deny: true            # Policy DROP for INPUT and FORWARD
    safety_net: true              # Enables Onyx Safety Net

    # --- ACTIVE INTELLIGENCE & RETALIATION ---
    sentinel_trap: true           # Enable Retaliatory Honey Port
    tarpit_trap: false            # Engage TARPIT for connection attempts
    geo_blocking: true            # Enable Geo-Blocking of high-risk countries
    unbound_filtered: true        # Enable Unbound DNS Filtering
    telemetry_blackout: true      # Blocks telemetry and analytics traffic
    
    # --- TUNNEL STEALTH ENHANCEMENTS ---
    mtu_stealth: true              # Force TCP handshake to use the tunnel's specific MTU to prevent 'Oversized Packet' detection
    webrtc_lockdown: true          # Blocks WebRTC IP leaks
    port_scrambling: true          # Randomize port numbers to prevent correlation

    # --- TRAFFIC INTEGRITY & OBFUSCATION ---
    ghost_host: true               # Disables Host Discovery and Broadcasts
    syn_proxy: true                # TCP SYN Proxy
    bogom_filter: true             # Drop malformed packets
    isolation_barrier: true        # VLAN-to-LAN separation (vlan20 -> uap0)
    packet_padding: false          # Obfuscate packet size and timing